**Import necessary libraries**
```{r}
library(data.table)
library(tidyverse)
library(broom)
library(lmerTest)
library(mice)
library(miceadds)
library(MuMIn)
library(stargazer)
library(lattice)
library(simr)
library(car)
```

**Load data and relevel factors function**
```{r}
Load.Clean.Data <- function(File = 'C:/Users/Cole/Documents/GRA_Summer2019/MasterDiagnosticDataConstruction/MasterData.csv',
                            assessment, impute = FALSE) {
  
  df <- fread(File)
  if(impute){
    vars <- c('Class_Standing', 'Gender', 'URM_Status', 'First_Gen_Status', 'GPA', 'AP_Calculus_AB', 'AP_Calculus_BC', 'ACT_SAT_Math_Percentile', 'PreScores', 'PostScores', 'Season', 'Sequence', 'Course_Content', 'Class')
    df.assessment <- df[Assessment == assessment]
    # df.assessment <- df[Assessment == assessment & (!is.na(PreScores) | !is.na(PostScores))]
  } else {
    vars <- c('Class_Standing', 'Gender', 'URM_Status', 'First_Gen_Status', 'AP_Calculus_AB', 'AP_Calculus_BC',
    'ACT_SAT_Math_Percentile', 'PreScores', 'PostScores', 'Season', 'Sequence', 'Course_Content', 'Class')
    df.assessment <- df[Assessment == assessment & (!is.na(PreScores) & !is.na(PostScores))]
  }
  
  df.assessment <- df.assessment %>%
    select(vars) %>%
    mutate(Class_Standing = relevel(as.factor(case_when(
      Class_Standing == 'Fresh' ~ 'FY',
      Class_Standing == 'Sophomore' | Class_Standing == 'Junior' | Class_Standing == 'Senior' ~ 'BFY',
      TRUE ~ NA_character_
    )), ref = 'FY'),
    Gender = relevel(as.factor(Gender), ref = 'M'),
    URM_Status = relevel(as.factor(URM_Status), ref = 'Majority'),
    First_Gen_Status = relevel(as.factor(First_Gen_Status), ref = 'ContGen'),
    AP_Calculus_AB = relevel(as.factor(AP_Calculus_AB), ref = 'NotTaken'),
    AP_Calculus_BC = relevel(as.factor(AP_Calculus_BC), ref = 'NotTaken'),
    Season = relevel(as.factor(Season), ref = 'FA'),
    Sequence = relevel(as.factor(Sequence), ref = 'Engineering'),
    Course_Content = as.factor(Course_Content),
    Class = as.factor(Class),
    ACT_SAT_Math_Percentile = c(scale(ACT_SAT_Math_Percentile, scale = TRUE)),
    PreScores = c(scale(PreScores, scale = TRUE)),
    PostScores = c(scale(PostScores, scale = TRUE)))
  
  if(impute){
    levels(df.assessment$Class) <- 1:length(levels(df.assessment$Class))
    df.assessment$Class <- as.numeric(df.assessment$Class)
    
    Frac.Missing <- round(sum(is.na(df.assessment$PreScores) |
                                is.na(df.assessment$PostScores))/nrow(df.assessment) * 100)
    print(Frac.Missing)
    
    ini <- mice(df.assessment, maxit = 0)
    predM <- ini$predictorMatrix
    iniM <- ini$method
    
    predM[, 'Class'] <- -2
    # print(iniM)
    iniM <- c('', '', '', '', '', '', '', '', '2l.pmm', '2l.pmm', '', '', '', '')
    # iniM <- c('', '', '', '', '', '', '', '2l.pmm', '2l.pmm', '', '', '', '')
    
    set.seed(11)
    imp.dat <- mice(df.assessment, m = Frac.Missing, pred = predM, met = iniM, print = FALSE)
    return(imp.dat)
  }
  return(df.assessment)
                            }
```

**Fits function**
```{r}
Do.Regressions <- function(dat, assessment) {
  fit0 <- lmer(PostScores ~ (1 | Class), dat)
  print(summary(fit0))
  print(r.squaredGLMM(fit0))
  print(AIC(fit0))
  
  fit1a <- lmer(PostScores ~ Gender + (1 | Class), dat)
  print(summary(fit1a))
  print(r.squaredGLMM(fit1a))
  print(AIC(fit1a))
  
  fit1b <- lmer(PostScores ~ URM_Status + (1 | Class), dat)
  print(summary(fit1b))
  print(r.squaredGLMM(fit1b))
  print(AIC(fit1b))
  
  fit1c <- lmer(PostScores ~ Class_Standing + (1 | Class), dat)
  print(summary(fit1c))
  print(r.squaredGLMM(fit1c))
  print(AIC(fit1c))
  
  fit1d <- lmer(PostScores ~ First_Gen_Status + (1 | Class), dat)
  print(summary(fit1d))
  print(r.squaredGLMM(fit1d))
  print(AIC(fit1d))
  
  fit2 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + (1 | Class), dat)
  print(summary(fit2))
  print(r.squaredGLMM(fit2))
  print(AIC(fit2))
  
  fit3 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + (1 | Class), dat)
  print(summary(fit3))
  print(r.squaredGLMM(fit3))
  print(AIC(fit3))
  
  fit4 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + (1 | Class), dat)
  print(summary(fit4))
  print(r.squaredGLMM(fit4))
  print(AIC(fit4))
  
  if(assessment == 'PLIC' | assessment == 'ECLASS'){
    fit5 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + Course_Content + (1 | Class), dat, na.action = "na.fail")
    #fit6 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + Season + Sequence + Course_Content + (1 | Class), dat)
  } else {
    fit5 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + (1 | Class), dat, na.action = "na.fail")
    #fit6 <- lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + Season + Sequence + (1 | Class), dat)
  }
  print(summary(fit5))
  print(r.squaredGLMM(fit5))
  print(AIC(fit5))
  
  #fit6 <- get.models(dredge(fit5, rank = 'AIC'), subset = 1)[[1]]
    
  #print(summary(fit6))
  #print(r.squaredGLMM(fit6))
  #print(AIC(fit6))
  
  class(fit0) <- "lmerMod"
  class(fit1a) <- "lmerMod"
  class(fit1b) <- "lmerMod"
  class(fit1c) <- "lmerMod"
  class(fit1d) <- "lmerMod"
  class(fit2) <- "lmerMod"
  class(fit3) <- "lmerMod"
  class(fit4) <- "lmerMod"
  class(fit5) <- "lmerMod"
  #class(fit6) <- "lmerMod"
  
  #stargazer(fit0, fit1a, fit1b, fit1c, fit1d, fit2, fit3, fit4, fit5, fit6, star.cutoffs = c(0.05, 0.01, 0.001), intercept.bottom = FALSE, out = paste(assessment, '.tex'), intercept.top = TRUE, omit.stat = 'all')
  
  # dat$resid <- resid(fit5)
  # dat$resid.abs <- abs(dat$resid)
  # dat$resid.abs.2 <- dat$resid.abs^2
  # dat$pred <- fitted(fit5)
  
  Coefs.summary <- rbind(rbind(tidy(fit1a), tidy(fit1b), tidy(fit1c), tidy(fit1d)) %>% mutate(Model = 1), tidy(fit2) %>% mutate(Model = 2), tidy(fit3) %>% mutate(Model = 3), tidy(fit5) %>% mutate(Model = 5))
  
  return(list("model" = fit5, "dataframe" = dat, 'Coefs' = Coefs.summary))
}
```

**PLIC Regressions**
```{r}
df.PLIC <- Load.Clean.Data(assessment = 'PLIC')

df.PLIC.fit5 <-  Do.Regressions(df.PLIC, assessment = 'PLIC')

plot(df.PLIC.fit5$model, xlab = 'Fitted values', ylab = 'Residuals')

PLIC.Coefs <- df.PLIC.fit5$Coefs

vif(df.PLIC.fit5$model)

# boxplot(resid.abs.2 ~ Class, df.PLIC.fit5$dataframe)
# anova(lm(resid.abs.2 ~ Class, data = df.PLIC.fit5$dataframe))

qqmath(df.PLIC.fit5$model)
```

**ECLASS Regressions**
```{r}
df.ECLASS <- Load.Clean.Data(assessment = 'ECLASS')

df.ECLASS.fit5 <- Do.Regressions(df.ECLASS, assessment = 'ECLASS')

plot(df.ECLASS.fit5$model, xlab = 'Fitted values', ylab = 'Residuals')

ECLASS.Coefs <- df.ECLASS.fit5$Coefs

vif(df.ECLASS.fit5$model)

# boxplot(resid.abs.2 ~ Class, df.ECLASS.fit5$dataframe)
# anova(lm(resid.abs.2 ~ Class, data = df.ECLASS.fit5$dataframe))

qqmath(df.ECLASS.fit5$model)
```

**MBT Regressions**
```{r}
df.MBT <- Load.Clean.Data(assessment = 'MBT')

df.MBT.fit5 <- Do.Regressions(df.MBT, assessment = 'MBT')

plot(df.MBT.fit5$model, xlab = 'Fitted values', ylab = 'Residuals')

MBT.Coefs <- df.MBT.fit5$Coefs

vif(df.MBT.fit5$model)

# boxplot(resid.abs.2 ~ Class, df.MBT.fit5$dataframe)
# anova(lm(resid.abs.2 ~ Class, data = df.MBT.fit5$dataframe))

qqmath(df.MBT.fit5$model)
```

**CSEM Regressions**
```{r}
df.CSEM <- Load.Clean.Data(assessment = 'CSEM')

df.CSEM.fit5 <- Do.Regressions(df.CSEM, assessment = 'CSEM')

plot(df.CSEM.fit5$model, xlab = 'Fitted values', ylab = 'Residuals')

CSEM.Coefs <- df.CSEM.fit5$Coefs

vif(df.CSEM.fit5$model)

# boxplot(resid.abs.2 ~ Class, df.CSEM.fit5$dataframe)
# anova(lm(resid.abs.2 ~ Class, data = df.CSEM.fit5$dataframe))

qqmath(df.CSEM.fit5$model)
```

**Aggregate Statistics**

**Plot fixed effects**
```{r}
Coefs <- rbind(PLIC.Coefs %>% mutate(Assessment = 'PLIC'), ECLASS.Coefs %>% mutate(Assessment = 'E-CLASS'), MBT.Coefs %>% mutate(Assessment = 'MBT'), CSEM.Coefs %>% mutate(Assessment = 'CSEM')) %>%
  filter(term == 'GenderF' | term == 'URM_StatusURM' | term == 'Class_StandingBFY' | term == 'First_Gen_StatusFirstGen') %>%
  mutate(Model = as.character(Model),
         Assessment = factor(Assessment, levels = c('MBT', 'CSEM', 'E-CLASS', 'PLIC')))

ggplot(Coefs, aes(x = Model, y = estimate, group = term, color = term)) +
  geom_point(aes(shape = term), size = 3, show.legend = FALSE) +
  geom_errorbar(aes(ymin = (estimate - std.error), ymax = (estimate + std.error)), width = 0.15,
                size = 1) +
  geom_line(size = 1) +
  facet_grid(rows = vars(Assessment), scales = "free") +
  theme_classic(base_size = 14) +
  theme(legend.title = element_blank(), 
        legend.position = 'top',
        legend.text = element_text(size = 10)) +
  scale_color_discrete(breaks = c('GenderF', 'URM_StatusURM', 'Class_StandingBFY', 'First_Gen_StatusFirstGen'),
                       labels = c('Gender', 'URM status', 'Class standing', 'First-generation status')) +
  ylab('Coefficient')

# ggplot(Coefs, aes(x = Model, y = estimate, group = Assessment, color = Assessment)) +
#   geom_errorbar(aes(ymin = (estimate - std.error), ymax = (estimate + std.error)), width = 0.15) +
#   geom_line() +
#   facet_grid(cols = vars(term))
```


**Simulated Power Analysis**
```{r eval = FALSE, warning = FALSE}
Do.Simulated.Power <- function(model, var, fixed.eff, eff = -0.2, nsim = 1000){
  fixef(model)[fixed.eff] <- eff
  pow <- powerSim(model, test = fixed(var), progress = FALSE, nsim = nsim)
  return(pow)
}

lapply(list(c('Gender', 'GenderF'), c('URM_Status', 'URM_StatusURM'), c('Class_Standing', 'Class_StandingBFY')), function (x) {
  Do.Simulated.Power(model = df.PLIC.fit5$model, var = x[1], fixed.eff = x[2])
  })

lapply(list(c('Gender', 'GenderF'), c('URM_Status', 'URM_StatusURM'), c('Class_Standing', 'Class_StandingBFY'), c('First_Gen_Status', 'First_Gen_StatusFirstGen')), function (x) {
  Do.Simulated.Power(model = df.ECLASS.fit5$model, var = x[1], fixed.eff = x[2])
  })

lapply(list(c('Gender', 'GenderF'), c('Class_Standing', 'Class_StandingBFY'), c('First_Gen_Status', 'First_Gen_StatusFirstGen')), function (x) {
  Do.Simulated.Power(model = df.MBT.fit5$model, var = x[1], fixed.eff = x[2])
  })

lapply(list(c('URM_Status', 'URM_StatusURM'), c('First_Gen_Status', 'First_Gen_StatusFirstGen')), function (x) {
  Do.Simulated.Power(model = df.CSEM.fit5$model, var = x[1], fixed.eff = x[2])
  })
```

**Appendix: missing data**
```{r}
df.master <- fread('C:/Users/Cole/Documents/GRA_Summer2019/MasterDiagnosticDataConstruction/MasterData.csv')

# Matched
df.master[!is.na(PreScores) & !is.na(PostScores), .(.N,
                                                    avg.GPA = mean(GPA),
                                                    stderror.GPA = sd(GPA)/sqrt(.N),
                                                    avg.pre = mean(PreScores), 
                                                    sderror.pre = sd(PreScores)/sqrt(.N),
                                                    avg.post = mean(PostScores), 
                                                    sderror.post = sd(PostScores)/sqrt(.N)), Assessment]

# Valid Pre
df.master[!is.na(PreScores) & is.na(PostScores), .(N.pre = .N,
                                                   avg.GPA = mean(GPA),
                                                   stderror.GPA = sd(GPA)/sqrt(.N),
                                                   avg.pre = mean(PreScores),
                                                   sderror.pre = sd(PreScores)/sqrt(.N)), Assessment]

# Valid Post
df.master[is.na(PreScores) & !is.na(PostScores), .(N.post = .N,
                                                   avg.GPA = mean(GPA),
                                                   stderror.GPA = sd(GPA)/sqrt(.N),
                                                   avg.post = mean(PostScores),
                                                   sderror.post = sd(PostScores)/sqrt(.N)), Assessment]

# No Survey
df.master[is.na(PreScores) & is.na(PostScores), .(N.no = .N,
                                                  avg.GPA = mean(GPA),
                                                  stderror.GPA = sd(GPA)/sqrt(.N)), Assessment]
```

**Appendix: multiple imputation**
```{r}
Impute.Analayze <- function(assessment){
  df.imp <- Load.Clean.Data(assessment = assessment, impute = TRUE)
  if(assessment == 'ECLASS' | assessment == 'PLIC'){
    fit <- with(df.imp, lme4::lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + Course_Content + (1 | Class)))
  } else {
    fit <- with(df.imp, lme4::lmer(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + (1 | Class)))
  }
  print(summary(pool(fit)))
}

Impute.Analayze('MBT')
Impute.Analayze('CSEM')
Impute.Analayze('ECLASS')
Impute.Analayze('PLIC')
```


**Appendix: linear mixed models with small number of level-2 samples**
```{r}
df.MBT.fit5.lm <- lm(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + Class, data = df.MBT)

df.PLIC.fit5.lm <- lm(PostScores ~ Gender + URM_Status + Class_Standing + First_Gen_Status + PreScores + ACT_SAT_Math_Percentile + AP_Calculus_AB + AP_Calculus_BC + Season + Sequence + Course_Content + Class, data = df.PLIC)

stargazer(df.MBT.fit5$model, df.MBT.fit5.lm, intercept.bottom = FALSE, out = paste('MBT_LMcomp.tex'), intercept.top = TRUE, omit.stat = 'all')
```

